name: Test ESM Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build y-mongodb-provider
        run: |
          npm ci
          npm run build

      # I install the dependencies here and overwrite y-mongodb-provider with the just built version to use the latest version
      - name: Create ESM server
        run: |
          cd example-servers/esm
          npm ci
          cp -r $GITHUB_WORKSPACE/src $GITHUB_WORKSPACE/example-servers/esm/node_modules/y-mongodb-provider/
          cp -r $GITHUB_WORKSPACE/dist $GITHUB_WORKSPACE/example-servers/esm/node_modules/y-mongodb-provider/
          cp $GITHUB_WORKSPACE/package.json $GITHUB_WORKSPACE/example-servers/esm/node_modules/y-mongodb-provider/
          npm run build

      # Afterwards I run it and kill it after 5 seconds to get the console output
      - name: Create and run ESM server
        id: scripts
        env:
          PORT: 3000
          MONGO_URL: 'mongodb://127.0.0.1:27017/todos' # doesnt really matter for this test since we dont need to connect
        run: |
          cd example-servers/esm
          npm run start &>> output.txt & SERVER_PID=$!
          sleep 5
          kill $SERVER_PID
          cat output.txt

      # We currently only check if the console output contains the "Yjs was already imported" error message
      - name: Check console output
        run: |
          cd example-servers/esm
          CONSOLE_OUTPUT=$(cat output.txt)
          echo "$CONSOLE_OUTPUT"
          if echo "$CONSOLE_OUTPUT" | grep -q "Yjs was already imported"; then
            echo "Error message found in console output"
            exit 1
          else
            echo "No error message found in console output"
          fi
        shell: bash
