name: Run Tests

on:
  pull_request:
    branches: [main]

strategy:
  matrix:
    node-version: ['14.x', '16.x', '18.x', '20.x']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test
